[package]
name = "reqwest-backoff"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11"
thiserror = "1.0"
tokio = "1.32"
url = "2.4.1"
tracing = "0.1"
chrono = "0.4.31"
